### ISSUE TITLE
Unable to get app running

### ISSUE THREAD

**Issue by laurenf** [devzero-inc/to-do-list#2]
After running `docker compose up` nothing shows at `localhost:3000`. I can see in the logs: `web-1  | Listening on http://[::]:3000`.

**Comment by AdoshSingh** [comment]
Working on it.

**Comment by AdoshSingh** [comment]
I have made the necessary changes:
 - now building and serving in a single command
 - not installing devDependencies in the docker 
 
Also updated CI to check if the everything is up and running,
https://github.com/devzero-inc/to-do-list/actions/runs/8019201419/job/21906634826

**Comment by AdoshSingh** [comment]
Added a healthcheck endpoint in the app.
Added a logging container which logs the whole server address (http://localhost:3000) when the app is up and running.

Branch: https://github.com/devzero-inc/to-do-list/tree/bug-fix/fixed-server-logging
PR: https://github.com/devzero-inc/to-do-list/pull/4
